services:

  app:
    build:
      context: .
      target: app
    ports:
      - 8000:80
    volumes:
      - .:/src
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379
